# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#ci:
#    skip: [clang-tidy, cppcheck, cmake-lint]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
      exclude: ^tests/.*/data/.*$
    - id: end-of-file-fixer
      exclude:  ^tests/.*/data/.*$
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
    - id: cmake-format
#    - id: cmake-lint
#- repo: https://github.com/pocc/pre-commit-hooks
#  rev: v1.3.5
#  hooks:
#      - id: clang-tidy
#        args: [-checks=clang-diagnostic-return-type]
#      - id: cppcheck
#        args: [--enable=all]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.44.0
  hooks:
  - id: markdownlint
    args: [-f]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v20.1.0
  hooks:
  - id: clang-format
    types_or: [c++, c, cuda]
